/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures;
use futures::{Future, Stream};

use super::{Error, configuration};

pub struct ArticlesApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> ArticlesApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> ArticlesApiClient<C> {
        ArticlesApiClient {
            configuration: configuration,
        }
    }
}

pub trait ArticlesApi {
    fn ArticleReviewsGet(&self, article_id: Vec<String>, article_model_id: Vec<String>, min_star_rating: &str, max_star_rating: &str, sort: &str, page: &str, page_size: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleReviews, Error = Error>>;
    fn ArticleReviewsReviewIdGet(&self, review_id: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleReview, Error = Error>>;
    fn ArticleReviewsSummariesArticleModelIdGet(&self, article_model_id: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleReviewsSummary, Error = Error>>;
    fn ArticleReviewsSummariesGet(&self, article_model_id: Vec<String>, page: &str, page_size: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleReviewsSummaries, Error = Error>>;
    fn ArticlesArticleIdGet(&self, article_id: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Article, Error = Error>>;
    fn ArticlesArticleIdMediaGet(&self, article_id: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleMedia, Error = Error>>;
    fn ArticlesArticleIdReviewsGet(&self, article_id: &str, min_star_rating: &str, max_star_rating: &str, sort: &str, page: &str, page_size: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleReviews, Error = Error>>;
    fn ArticlesArticleIdReviewsSummaryGet(&self, article_id: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleReviewsSummary, Error = Error>>;
    fn ArticlesArticleIdUnitsGet(&self, article_id: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleUnits, Error = Error>>;
    fn ArticlesArticleIdUnitsUnitIdGet(&self, article_id: &str, unit_id: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleUnit, Error = Error>>;
    fn ArticlesGet(&self, article_id: Vec<String>, article_model_id: Vec<String>, article_unit_id: Vec<String>, activation_date: Vec<String>, age_group: Vec<String>, assortment_area: Vec<String>, brand: Vec<String>, brandfamily: Vec<String>, category: Vec<String>, color: Vec<String>, den: Vec<String>, filling: Vec<String>, full_text: &str, gender: Vec<String>, heel_form: Vec<String>, heel_height: Vec<String>, length: &str, occasion: Vec<String>, pattern: Vec<String>, price: &str, sale: Vec<String>, season: Vec<String>, shaft_height: Vec<String>, shaft_width: Vec<String>, shirt_collar: Vec<String>, shoe_fastener: Vec<String>, shoe_toecap: Vec<String>, shop_area: Vec<String>, size: &str, sports: Vec<String>, technology: Vec<String>, trouser_rise: Vec<String>, upper_material: Vec<String>, volume: Vec<String>, page: &str, page_size: &str, sort: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Articles, Error = Error>>;
}


impl<C: hyper::client::Connect>ArticlesApi for ArticlesApiClient<C> {
    fn ArticleReviewsGet(&self, article_id: Vec<String>, article_model_id: Vec<String>, min_star_rating: &str, max_star_rating: &str, sort: &str, page: &str, page_size: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleReviews, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("articleId", &article_id.join(",").to_string())
            .append_pair("articleModelId", &article_model_id.join(",").to_string())
            .append_pair("minStarRating", &min_star_rating.to_string())
            .append_pair("maxStarRating", &max_star_rating.to_string())
            .append_pair("sort", &sort.to_string())
            .append_pair("page", &page.to_string())
            .append_pair("pageSize", &page_size.to_string())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/article-reviews{}", configuration.base_path, query);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::ArticleReviews, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn ArticleReviewsReviewIdGet(&self, review_id: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleReview, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/article-reviews/{reviewId}{}", configuration.base_path, query, reviewId=review_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::ArticleReview, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn ArticleReviewsSummariesArticleModelIdGet(&self, article_model_id: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleReviewsSummary, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/article-reviews-summaries/{articleModelId}{}", configuration.base_path, query, articleModelId=article_model_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::ArticleReviewsSummary, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn ArticleReviewsSummariesGet(&self, article_model_id: Vec<String>, page: &str, page_size: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleReviewsSummaries, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("articleModelId", &article_model_id.join(",").to_string())
            .append_pair("page", &page.to_string())
            .append_pair("pageSize", &page_size.to_string())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/article-reviews-summaries{}", configuration.base_path, query);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::ArticleReviewsSummaries, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn ArticlesArticleIdGet(&self, article_id: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Article, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/articles/{articleId}{}", configuration.base_path, query, articleId=article_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::Article, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn ArticlesArticleIdMediaGet(&self, article_id: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleMedia, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/articles/{articleId}/media{}", configuration.base_path, query, articleId=article_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::ArticleMedia, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn ArticlesArticleIdReviewsGet(&self, article_id: &str, min_star_rating: &str, max_star_rating: &str, sort: &str, page: &str, page_size: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleReviews, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("minStarRating", &min_star_rating.to_string())
            .append_pair("maxStarRating", &max_star_rating.to_string())
            .append_pair("sort", &sort.to_string())
            .append_pair("page", &page.to_string())
            .append_pair("pageSize", &page_size.to_string())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/articles/{articleId}/reviews{}", configuration.base_path, query, articleId=article_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::ArticleReviews, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn ArticlesArticleIdReviewsSummaryGet(&self, article_id: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleReviewsSummary, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/articles/{articleId}/reviews-summary{}", configuration.base_path, query, articleId=article_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::ArticleReviewsSummary, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn ArticlesArticleIdUnitsGet(&self, article_id: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleUnits, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/articles/{articleId}/units{}", configuration.base_path, query, articleId=article_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::ArticleUnits, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn ArticlesArticleIdUnitsUnitIdGet(&self, article_id: &str, unit_id: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::ArticleUnit, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/articles/{articleId}/units/{unitId}{}", configuration.base_path, query, articleId=article_id, unitId=unit_id);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::ArticleUnit, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn ArticlesGet(&self, article_id: Vec<String>, article_model_id: Vec<String>, article_unit_id: Vec<String>, activation_date: Vec<String>, age_group: Vec<String>, assortment_area: Vec<String>, brand: Vec<String>, brandfamily: Vec<String>, category: Vec<String>, color: Vec<String>, den: Vec<String>, filling: Vec<String>, full_text: &str, gender: Vec<String>, heel_form: Vec<String>, heel_height: Vec<String>, length: &str, occasion: Vec<String>, pattern: Vec<String>, price: &str, sale: Vec<String>, season: Vec<String>, shaft_height: Vec<String>, shaft_width: Vec<String>, shirt_collar: Vec<String>, shoe_fastener: Vec<String>, shoe_toecap: Vec<String>, shop_area: Vec<String>, size: &str, sports: Vec<String>, technology: Vec<String>, trouser_rise: Vec<String>, upper_material: Vec<String>, volume: Vec<String>, page: &str, page_size: &str, sort: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Articles, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("articleId", &article_id.join(",").to_string())
            .append_pair("articleModelId", &article_model_id.join(",").to_string())
            .append_pair("articleUnitId", &article_unit_id.join(",").to_string())
            .append_pair("activationDate", &activation_date.join(",").to_string())
            .append_pair("ageGroup", &age_group.join(",").to_string())
            .append_pair("assortmentArea", &assortment_area.join(",").to_string())
            .append_pair("brand", &brand.join(",").to_string())
            .append_pair("brandfamily", &brandfamily.join(",").to_string())
            .append_pair("category", &category.join(",").to_string())
            .append_pair("color", &color.join(",").to_string())
            .append_pair("den", &den.join(",").to_string())
            .append_pair("filling", &filling.join(",").to_string())
            .append_pair("fullText", &full_text.to_string())
            .append_pair("gender", &gender.join(",").to_string())
            .append_pair("heelForm", &heel_form.join(",").to_string())
            .append_pair("heelHeight", &heel_height.join(",").to_string())
            .append_pair("length", &length.to_string())
            .append_pair("occasion", &occasion.join(",").to_string())
            .append_pair("pattern", &pattern.join(",").to_string())
            .append_pair("price", &price.to_string())
            .append_pair("sale", &sale.join(",").to_string())
            .append_pair("season", &season.join(",").to_string())
            .append_pair("shaftHeight", &shaft_height.join(",").to_string())
            .append_pair("shaftWidth", &shaft_width.join(",").to_string())
            .append_pair("shirtCollar", &shirt_collar.join(",").to_string())
            .append_pair("shoeFastener", &shoe_fastener.join(",").to_string())
            .append_pair("shoeToecap", &shoe_toecap.join(",").to_string())
            .append_pair("shopArea", &shop_area.join(",").to_string())
            .append_pair("size", &size.to_string())
            .append_pair("sports", &sports.join(",").to_string())
            .append_pair("technology", &technology.join(",").to_string())
            .append_pair("trouserRise", &trouser_rise.join(",").to_string())
            .append_pair("upperMaterial", &upper_material.join(",").to_string())
            .append_pair("volume", &volume.join(",").to_string())
            .append_pair("page", &page.to_string())
            .append_pair("pageSize", &page_size.to_string())
            .append_pair("sort", &sort.to_string())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/articles{}", configuration.base_path, query);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::Articles, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

}
