/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures;
use futures::{Future, Stream};

use super::{Error, configuration};

pub struct BrandsApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> BrandsApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> BrandsApiClient<C> {
        BrandsApiClient {
            configuration: configuration,
        }
    }
}

pub trait BrandsApi {
    fn BrandsGet(&self, key: Vec<String>, name: Vec<String>, brand_family_name: Vec<String>, brand_family_key: Vec<String>, page: &str, page_size: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Brands, Error = Error>>;
    fn BrandsKeyGet(&self, key: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Brand, Error = Error>>;
}


impl<C: hyper::client::Connect>BrandsApi for BrandsApiClient<C> {
    fn BrandsGet(&self, key: Vec<String>, name: Vec<String>, brand_family_name: Vec<String>, brand_family_key: Vec<String>, page: &str, page_size: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Brands, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("key", &key.join(",").to_string())
            .append_pair("name", &name.join(",").to_string())
            .append_pair("brandFamilyName", &brand_family_name.join(",").to_string())
            .append_pair("brandFamilyKey", &brand_family_key.join(",").to_string())
            .append_pair("page", &page.to_string())
            .append_pair("pageSize", &page_size.to_string())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/brands{}", configuration.base_path, query);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::Brands, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn BrandsKeyGet(&self, key: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Brand, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/brands/{key}{}", configuration.base_path, query, key=key);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::Brand, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

}
