/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures;
use futures::{Future, Stream};

use super::{Error, configuration};

pub struct CategoriesApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> CategoriesApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> CategoriesApiClient<C> {
        CategoriesApiClient {
            configuration: configuration,
        }
    }
}

pub trait CategoriesApi {
    fn CategoriesGet(&self, name: Vec<String>, _type: &str, outlet: &str, hidden: &str, target_group: &str, key: Vec<String>, parent_key: Vec<String>, child_key: Vec<String>, suggested_filter: Vec<String>, page: &str, page_size: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Categories, Error = Error>>;
    fn CategoriesKeyGet(&self, key: Vec<String>, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Category, Error = Error>>;
}


impl<C: hyper::client::Connect>CategoriesApi for CategoriesApiClient<C> {
    fn CategoriesGet(&self, name: Vec<String>, _type: &str, outlet: &str, hidden: &str, target_group: &str, key: Vec<String>, parent_key: Vec<String>, child_key: Vec<String>, suggested_filter: Vec<String>, page: &str, page_size: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Categories, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("name", &name.join(",").to_string())
            .append_pair("type", &_type.to_string())
            .append_pair("outlet", &outlet.to_string())
            .append_pair("hidden", &hidden.to_string())
            .append_pair("targetGroup", &target_group.to_string())
            .append_pair("key", &key.join(",").to_string())
            .append_pair("parentKey", &parent_key.join(",").to_string())
            .append_pair("childKey", &child_key.join(",").to_string())
            .append_pair("suggestedFilter", &suggested_filter.join(",").to_string())
            .append_pair("page", &page.to_string())
            .append_pair("pageSize", &page_size.to_string())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/categories{}", configuration.base_path, query);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::Categories, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn CategoriesKeyGet(&self, key: Vec<String>, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Category, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/categories/{key}{}", configuration.base_path, query, key=key.join(",").as_ref());

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::Category, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

}
