/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures;
use futures::{Future, Stream};

use super::{Error, configuration};

pub struct CategoriesApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> CategoriesApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> CategoriesApiClient<C> {
        CategoriesApiClient {
            configuration: configuration,
        }
    }
}

pub trait CategoriesApi {
    fn CategoriesGet(&self, name: Option<Vec<String>>, _type: Option<&str>, outlet: Option<&str>, hidden: Option<&str>, target_group: Option<&str>, key: Option<Vec<String>>, parent_key: Option<Vec<String>>, child_key: Option<Vec<String>>, suggested_filter: Option<Vec<String>>, page: Option<&str>, page_size: Option<&str>, accept_language: Option<&str>, fields: Option<Vec<String>>) -> Box<Future<Item = ::models::Categories, Error = Error>>;
    fn CategoriesKeyGet(&self, key: Vec<String>, accept_language: Option<&str>, fields: Option<Vec<String>>) -> Box<Future<Item = ::models::Category, Error = Error>>;
}


impl<C: hyper::client::Connect>CategoriesApi for CategoriesApiClient<C> {
   fn CategoriesGet(&self, name: Option<Vec<String>>, _type: Option<&str>, outlet: Option<&str>, hidden: Option<&str>, target_group: Option<&str>, key: Option<Vec<String>>, parent_key: Option<Vec<String>>, child_key: Option<Vec<String>>, suggested_filter: Option<Vec<String>>, page: Option<&str>, page_size: Option<&str>, accept_language: Option<&str>, fields: Option<Vec<String>>) -> Box<Future<Item = ::models::Categories, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let mut query = ::url::form_urlencoded::Serializer::new(String::new());
        match name{
           Some(value)=>{query.append_pair("name", &value.join(",").to_string());},
           None=>{},
        }
        match _type{
           Some(value)=>{query.append_pair("type", &value.to_string());},
           None=>{},
        }
        match outlet{
           Some(value)=>{query.append_pair("outlet", &value.to_string());},
           None=>{},
        }
        match hidden{
           Some(value)=>{query.append_pair("hidden", &value.to_string());},
           None=>{},
        }
        match target_group{
           Some(value)=>{query.append_pair("targetGroup", &value.to_string());},
           None=>{},
        }
        match key{
           Some(value)=>{query.append_pair("key", &value.join(",").to_string());},
           None=>{},
        }
        match parent_key{
           Some(value)=>{query.append_pair("parentKey", &value.join(",").to_string());},
           None=>{},
        }
        match child_key{
           Some(value)=>{query.append_pair("childKey", &value.join(",").to_string());},
           None=>{},
        }
        match suggested_filter{
           Some(value)=>{query.append_pair("suggestedFilter", &value.join(",").to_string());},
           None=>{},
        }
        match page{
           Some(value)=>{query.append_pair("page", &value.to_string());},
           None=>{},
        }
        match page_size{
           Some(value)=>{query.append_pair("pageSize", &value.to_string());},
           None=>{},
        }
        match fields{
           Some(value)=>{query.append_pair("fields", &value.join(",").to_string());},
           None=>{},
        }
        let finished_query=query.finish();
        let uri_str = format!("{}/categories{}", configuration.base_path, finished_query);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            match accept_language{
               Some(value)=>{headers.set_raw("Accept-Language", value);},
               None=>{},
            }
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::Categories, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

   fn CategoriesKeyGet(&self, key: Vec<String>, accept_language: Option<&str>, fields: Option<Vec<String>>) -> Box<Future<Item = ::models::Category, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let mut query = ::url::form_urlencoded::Serializer::new(String::new());
        match fields{
           Some(value)=>{query.append_pair("fields", &value.join(",").to_string());},
           None=>{},
        }
        let finished_query=query.finish();
        let uri_str = format!("{}/categories/{key}{}", configuration.base_path, finished_query, key=key.join(","));

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            match accept_language{
               Some(value)=>{headers.set_raw("Accept-Language", value);},
               None=>{},
            }
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::Category, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

}
