/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures;
use futures::{Future, Stream};

use super::{Error, configuration};

pub struct FiltersApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> FiltersApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> FiltersApiClient<C> {
        FiltersApiClient {
            configuration: configuration,
        }
    }
}

pub trait FiltersApi {
    fn FiltersFilterNameGet(&self, filter_name: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Filter, Error = Error>>;
    fn FiltersGet(&self, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Filters, Error = Error>>;
}


impl<C: hyper::client::Connect>FiltersApi for FiltersApiClient<C> {
    fn FiltersFilterNameGet(&self, filter_name: &str, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Filter, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/filters/{filterName}{}", configuration.base_path, query, filterName=filter_name);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::Filter, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

    fn FiltersGet(&self, accept_language: &str, fields: Vec<String>) -> Box<Future<Item = ::models::Filters, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let query = ::url::form_urlencoded::Serializer::new(String::new())
            .append_pair("fields", &fields.join(",").to_string())
            .finish();
        let uri_str = format!("{}/filters{}", configuration.base_path, query);

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            headers.set_raw("Accept-Language", accept_language);
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::Filters, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

}
