/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures;
use futures::{Future, Stream};

use super::{Error, configuration};

pub struct RecommendationsApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> RecommendationsApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> RecommendationsApiClient<C> {
        RecommendationsApiClient {
            configuration: configuration,
        }
    }
}

pub trait RecommendationsApi {
    fn RecommendationsArticleIdsGet(&self, article_ids: Vec<String>, max_results: Option<&str>, accept_language: Option<&str>, fields: Option<Vec<String>>) -> Box<Future<Item = ::models::Recommendations, Error = Error>>;
}


impl<C: hyper::client::Connect>RecommendationsApi for RecommendationsApiClient<C> {
    fn RecommendationsArticleIdsGet(&self, article_ids: Vec<String>, max_results: Option<&str>, accept_language: Option<&str>, fields: Option<Vec<String>>) -> Box<Future<Item = ::models::Recommendations, Error = Error>> {
        let configuration: &configuration::Configuration<C> = self.configuration.borrow();

        let method = hyper::Method::Get;

        let mut query = ::url::form_urlencoded::Serializer::new(String::new());
        match max_results{
           Some(value)=>{query.append_pair("maxResults", &value.to_string());},
           None=>{},
        }
        match fields{
           Some(value)=>{query.append_pair("fields", &value.join(",").to_string());},
           None=>{},
        }
        let finished_query=query.finish();
        let uri_str = format!("{}/recommendations/{articleIds}{}", configuration.base_path, finished_query, articleIds=article_ids.join(","));

        let uri = uri_str.parse();
        // TODO(farcaller): handle error
        // if let Err(e) = uri {
        //     return Box::new(futures::future::err(e));
        // }
        let mut req = hyper::Request::new(method, uri.unwrap());

        {
            let mut headers = req.headers_mut();
            match accept_language{
               Some(value)=>{headers.set_raw("Accept-Language", value);},
               None=>{},
            }
        }


        // send request
        Box::new(
            configuration.client.request(req).and_then(|res| { res.body().concat2() })
            .map_err(|e| Error::from(e))
            .and_then(|body| {
                let parsed: Result<::models::Recommendations, _> = serde_json::from_slice(&body);
                parsed.map_err(|e| Error::from(e))
            }).map_err(|e| Error::from(e))
        )
    }

}
