/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ArticleMedia : Zalando API Article Media Schema

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ArticleMedia {
  #[serde(rename = "images")] images: Vec<::models::ArticleImage>
}

impl ArticleMedia {
  /// Zalando API Article Media Schema
  pub fn new(images: Vec<::models::ArticleImage>) -> ArticleMedia {
    ArticleMedia {
      images: images
    }
  }

  pub fn set_images(&mut self, images: Vec<::models::ArticleImage>) {
    self.images = images;
  }

  pub fn with_images(mut self, images: Vec<::models::ArticleImage>) -> ArticleMedia {
    self.images = images;
    self
  }

  pub fn images(&self) -> &Vec<::models::ArticleImage> {
    &self.images
  }

}



