/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ArticleAttribute : Zalando API Article Attribute Schema

#[derive(Debug, Serialize, Deserialize)]
pub struct ArticleAttribute {
  /// name of the article attribute
  #[serde(rename = "name")] name: String,
  /// value of the article attribute
  #[serde(rename = "values")] values: Vec<String>
}

impl ArticleAttribute {
  /// Zalando API Article Attribute Schema
  pub fn new(name: String, values: Vec<String>) -> ArticleAttribute {
    ArticleAttribute {
      name: name,
      values: values
    }
  }

  pub fn set_name(&mut self, name: String) {
    self.name = name;
  }

  pub fn with_name(mut self, name: String) -> ArticleAttribute {
    self.name = name;
    self
  }

  pub fn name(&self) -> &String {
    &self.name
  }

  pub fn set_values(&mut self, values: Vec<String>) {
    self.values = values;
  }

  pub fn with_values(mut self, values: Vec<String>) -> ArticleAttribute {
    self.values = values;
    self
  }

  pub fn values(&self) -> &Vec<String> {
    &self.values
  }

}



