/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ArticleUnits : Zalando API Article Units Schema

#[derive(Debug, Serialize, Deserialize)]
pub struct ArticleUnits {
}

impl ArticleUnits {
  /// Zalando API Article Units Schema
  pub fn new() -> ArticleUnits {
    ArticleUnits {
    }
  }

}



