/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ArticleImage : Zalando API Article Image Schema

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ArticleImage {
  /// sequence of the article images
  #[serde(rename = "orderNumber")] order_number: i32,
  /// model or non model type article images
  #[serde(rename = "type")] _type: String,
  /// thumbnail HD url of the article images
  #[serde(rename = "thumbnailHdUrl")] thumbnail_hd_url: String,
  /// small image of the article
  #[serde(rename = "smallUrl")] small_url: String,
  /// small HD image of the article
  #[serde(rename = "smallHdUrl")] small_hd_url: String,
  /// medium image of the article
  #[serde(rename = "mediumUrl")] medium_url: String,
  /// medium HD image of the article
  #[serde(rename = "mediumHdUrl")] medium_hd_url: String,
  /// large image of the article
  #[serde(rename = "largeUrl")] large_url: String,
  /// large HD image of the article
  #[serde(rename = "largeHdUrl")] large_hd_url: String
}

impl ArticleImage {
  /// Zalando API Article Image Schema
  pub fn new(order_number: i32, _type: String, thumbnail_hd_url: String, small_url: String, small_hd_url: String, medium_url: String, medium_hd_url: String, large_url: String, large_hd_url: String) -> ArticleImage {
    ArticleImage {
      order_number: order_number,
      _type: _type,
      thumbnail_hd_url: thumbnail_hd_url,
      small_url: small_url,
      small_hd_url: small_hd_url,
      medium_url: medium_url,
      medium_hd_url: medium_hd_url,
      large_url: large_url,
      large_hd_url: large_hd_url
    }
  }

  pub fn set_order_number(&mut self, order_number: i32) {
    self.order_number = order_number;
  }

  pub fn with_order_number(mut self, order_number: i32) -> ArticleImage {
    self.order_number = order_number;
    self
  }

  pub fn order_number(&self) -> &i32 {
    &self.order_number
  }

  pub fn set__type(&mut self, _type: String) {
    self._type = _type;
  }

  pub fn with__type(mut self, _type: String) -> ArticleImage {
    self._type = _type;
    self
  }

  pub fn _type(&self) -> &String {
    &self._type
  }

  pub fn set_thumbnail_hd_url(&mut self, thumbnail_hd_url: String) {
    self.thumbnail_hd_url = thumbnail_hd_url;
  }

  pub fn with_thumbnail_hd_url(mut self, thumbnail_hd_url: String) -> ArticleImage {
    self.thumbnail_hd_url = thumbnail_hd_url;
    self
  }

  pub fn thumbnail_hd_url(&self) -> &String {
    &self.thumbnail_hd_url
  }

  pub fn set_small_url(&mut self, small_url: String) {
    self.small_url = small_url;
  }

  pub fn with_small_url(mut self, small_url: String) -> ArticleImage {
    self.small_url = small_url;
    self
  }

  pub fn small_url(&self) -> &String {
    &self.small_url
  }

  pub fn set_small_hd_url(&mut self, small_hd_url: String) {
    self.small_hd_url = small_hd_url;
  }

  pub fn with_small_hd_url(mut self, small_hd_url: String) -> ArticleImage {
    self.small_hd_url = small_hd_url;
    self
  }

  pub fn small_hd_url(&self) -> &String {
    &self.small_hd_url
  }

  pub fn set_medium_url(&mut self, medium_url: String) {
    self.medium_url = medium_url;
  }

  pub fn with_medium_url(mut self, medium_url: String) -> ArticleImage {
    self.medium_url = medium_url;
    self
  }

  pub fn medium_url(&self) -> &String {
    &self.medium_url
  }

  pub fn set_medium_hd_url(&mut self, medium_hd_url: String) {
    self.medium_hd_url = medium_hd_url;
  }

  pub fn with_medium_hd_url(mut self, medium_hd_url: String) -> ArticleImage {
    self.medium_hd_url = medium_hd_url;
    self
  }

  pub fn medium_hd_url(&self) -> &String {
    &self.medium_hd_url
  }

  pub fn set_large_url(&mut self, large_url: String) {
    self.large_url = large_url;
  }

  pub fn with_large_url(mut self, large_url: String) -> ArticleImage {
    self.large_url = large_url;
    self
  }

  pub fn large_url(&self) -> &String {
    &self.large_url
  }

  pub fn set_large_hd_url(&mut self, large_hd_url: String) {
    self.large_hd_url = large_hd_url;
  }

  pub fn with_large_hd_url(mut self, large_hd_url: String) -> ArticleImage {
    self.large_hd_url = large_hd_url;
    self
  }

  pub fn large_hd_url(&self) -> &String {
    &self.large_hd_url
  }

}



