/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// BrandFamily : Zalando API BrandFamily Schema

#[derive(Debug, Serialize, Deserialize)]
pub struct BrandFamily {
  /// The unique key for a brandFamily
  #[serde(rename = "key")] key: String,
  /// Name of the brandFamily
  #[serde(rename = "name")] name: String,
  /// The url of the brandFamily within the Zalando web shop
  #[serde(rename = "shopUrl")] shop_url: String
}

impl BrandFamily {
  /// Zalando API BrandFamily Schema
  pub fn new(key: String, name: String, shop_url: String) -> BrandFamily {
    BrandFamily {
      key: key,
      name: name,
      shop_url: shop_url
    }
  }

  pub fn set_key(&mut self, key: String) {
    self.key = key;
  }

  pub fn with_key(mut self, key: String) -> BrandFamily {
    self.key = key;
    self
  }

  pub fn key(&self) -> &String {
    &self.key
  }

  pub fn set_name(&mut self, name: String) {
    self.name = name;
  }

  pub fn with_name(mut self, name: String) -> BrandFamily {
    self.name = name;
    self
  }

  pub fn name(&self) -> &String {
    &self.name
  }

  pub fn set_shop_url(&mut self, shop_url: String) {
    self.shop_url = shop_url;
  }

  pub fn with_shop_url(mut self, shop_url: String) -> BrandFamily {
    self.shop_url = shop_url;
    self
  }

  pub fn shop_url(&self) -> &String {
    &self.shop_url
  }

}



