/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Facet : Zalando API Facet Schema

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Facet {
  #[serde(rename = "filter")] filter: String,
  /// list of the calculated article counts for each filter value
  #[serde(rename = "facets")] facets: Vec<::models::FacetValue>
}

impl Facet {
  /// Zalando API Facet Schema
  pub fn new(filter: String, facets: Vec<::models::FacetValue>) -> Facet {
    Facet {
      filter: filter,
      facets: facets
    }
  }

  pub fn set_filter(&mut self, filter: String) {
    self.filter = filter;
  }

  pub fn with_filter(mut self, filter: String) -> Facet {
    self.filter = filter;
    self
  }

  pub fn filter(&self) -> &String {
    &self.filter
  }

  pub fn set_facets(&mut self, facets: Vec<::models::FacetValue>) {
    self.facets = facets;
  }

  pub fn with_facets(mut self, facets: Vec<::models::FacetValue>) -> Facet {
    self.facets = facets;
    self
  }

  pub fn facets(&self) -> &Vec<::models::FacetValue> {
    &self.facets
  }

}



