/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// FacetValue : Zalando API FacetValue Schema

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct FacetValue {
  #[serde(rename = "key")] key: String,
  #[serde(rename = "displayName")] display_name: String,
  /// number of articles matching this filter value
  #[serde(rename = "count")] count: i32
}

impl FacetValue {
  /// Zalando API FacetValue Schema
  pub fn new(key: String, display_name: String, count: i32) -> FacetValue {
    FacetValue {
      key: key,
      display_name: display_name,
      count: count
    }
  }

  pub fn set_key(&mut self, key: String) {
    self.key = key;
  }

  pub fn with_key(mut self, key: String) -> FacetValue {
    self.key = key;
    self
  }

  pub fn key(&self) -> &String {
    &self.key
  }

  pub fn set_display_name(&mut self, display_name: String) {
    self.display_name = display_name;
  }

  pub fn with_display_name(mut self, display_name: String) -> FacetValue {
    self.display_name = display_name;
    self
  }

  pub fn display_name(&self) -> &String {
    &self.display_name
  }

  pub fn set_count(&mut self, count: i32) {
    self.count = count;
  }

  pub fn with_count(mut self, count: i32) -> FacetValue {
    self.count = count;
    self
  }

  pub fn count(&self) -> &i32 {
    &self.count
  }

}



