/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Facets : Zalando API Facets Schema

#[derive(Debug, Serialize, Deserialize)]
pub struct Facets {
}

impl Facets {
  /// Zalando API Facets Schema
  pub fn new() -> Facets {
    Facets {
    }
  }

}



