/* 
 * Zalando Shop API
 *
 * The shop API empowers developers to build amazing new apps or websites using Zalando shop data and services.
 *
 * OpenAPI spec version: v1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// Recommendations : Zalando API Recommendations Schema

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Recommendations {
}

impl Recommendations {
  /// Zalando API Recommendations Schema
  pub fn new() -> Recommendations {
    Recommendations {
    }
  }

}



